Revert "ci: Workaround for https://github.com/saltstack/relenv/issues/182"
This reverts commit 8a6919f2a36dcc8e82de9cf19261adf65e0e4a3c.

Now that https://github.com/saltstack/relenv/issues/182 is solved, this
workaround is no longer needed and actually causes a different error
now:

```
[ERROR   ] Command '/opt/saltstack/salt/salt-pip' failed with return code: 1
[ERROR   ] stdout: Collecting mysqlclient
  Downloading mysqlclient-2.2.8.tar.gz (92 kB)
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
[ERROR   ] stderr:   error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Could not find an up-to-date installation of `packaging`. License expressions might not be validated. To enforce validation, please install `packaging>=24.2`.
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      # Options for building extension module:
        extra_compile_args: ['-I/usr/include/mariadb/', '-std=c99']
        extra_link_args: ['-L/usr/lib/x86_64-linux-gnu/', '-lmariadb']
        define_macros: [('version_info', (2, 2, 8, 'final', 0)), ('__version__', '2.2.8')]
      Traceback (most recent call last):
        File "/opt/saltstack/salt/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/opt/saltstack/salt/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "/opt/saltstack/salt/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 175, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 169, in <module>
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)  # type: ignore[return-value]
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 160, in setup
          dist.parse_config_files()
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/dist.py", line 762, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 73, in apply_configuration
          return _apply(dist, config, filepath)
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 61, in apply
          dist._finalize_license_expression()
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/dist.py", line 425, in _finalize_license_expression
          normalized = str_(_canonicalize_license_expression(license_expr))
        File "/opt/saltstack/salt/lib/python3.10/site-packages/setuptools/_normalization.py", line 164, in _missing_canonicalize_license_expression
          raise ImportError(
      ImportError: Cannot import `packaging.licenses`.
              Setuptools>=77.0.0 requires "packaging>=24.2" to work properly.
              Please make sure you have a suitable version installed.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```